// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_top,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.241000,HLS_SYN_LAT=4709448,HLS_SYN_TPT=none,HLS_SYN_MEM=200,HLS_SYN_DSP=0,HLS_SYN_FF=4166,HLS_SYN_LUT=4126,HLS_VERSION=2020_2}" *)

module top (
        ap_clk,
        ap_rst_n,
        data_IN_TDATA,
        data_IN_TVALID,
        data_IN_TREADY,
        data_OUT_TDATA,
        data_OUT_TVALID,
        data_OUT_TREADY
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_pp2_stage0 = 19'd32;
parameter    ap_ST_fsm_state9 = 19'd64;
parameter    ap_ST_fsm_state10 = 19'd128;
parameter    ap_ST_fsm_state11 = 19'd256;
parameter    ap_ST_fsm_state12 = 19'd512;
parameter    ap_ST_fsm_pp3_stage0 = 19'd1024;
parameter    ap_ST_fsm_state19 = 19'd2048;
parameter    ap_ST_fsm_state20 = 19'd4096;
parameter    ap_ST_fsm_pp4_stage0 = 19'd8192;
parameter    ap_ST_fsm_state24 = 19'd16384;
parameter    ap_ST_fsm_pp5_stage0 = 19'd32768;
parameter    ap_ST_fsm_state28 = 19'd65536;
parameter    ap_ST_fsm_pp6_stage0 = 19'd131072;
parameter    ap_ST_fsm_state32 = 19'd262144;

input   ap_clk;
input   ap_rst_n;
input  [31:0] data_IN_TDATA;
input   data_IN_TVALID;
output   data_IN_TREADY;
output  [31:0] data_OUT_TDATA;
output   data_OUT_TVALID;
input   data_OUT_TREADY;

 reg    ap_rst_n_inv;
wire   [5:0] hamming_coeff_M_real_V_address0;
reg    hamming_coeff_M_real_V_ce0;
wire   [8:0] hamming_coeff_M_real_V_q0;
reg    data_IN_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln6_fu_507_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln10_fu_524_p2;
reg    data_OUT_TDATA_blk_n;
wire    ap_CS_fsm_pp5_stage0;
reg    ap_enable_reg_pp5_iter1;
wire    ap_block_pp5_stage0;
reg   [0:0] icmp_ln17_reg_1097;
reg    ap_enable_reg_pp5_iter2;
reg   [0:0] icmp_ln17_reg_1097_pp5_iter1_reg;
wire    ap_CS_fsm_pp6_stage0;
reg    ap_enable_reg_pp6_iter1;
wire    ap_block_pp6_stage0;
reg   [0:0] icmp_ln21_reg_1116;
reg    ap_enable_reg_pp6_iter2;
reg   [0:0] icmp_ln21_reg_1116_pp6_iter1_reg;
reg   [13:0] indvar_flatten_reg_346;
reg   [8:0] i_2_reg_357;
reg   [5:0] j_reg_368;
reg   [13:0] indvar_flatten7_reg_379;
reg   [8:0] i_3_reg_390;
reg   [5:0] j_1_reg_401;
reg   [13:0] indvar_flatten15_reg_412;
reg   [8:0] i_4_reg_423;
reg   [5:0] j_2_reg_434;
reg   [13:0] i_5_reg_445;
reg   [13:0] i_6_reg_456;
wire   [13:0] add_ln6_fu_501_p2;
reg    ap_block_state2;
wire   [13:0] add_ln10_fu_518_p2;
reg    ap_block_state4;
wire   [13:0] add_ln37_1_fu_535_p2;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state6_pp2_stage0_iter0;
wire    ap_block_state7_pp2_stage0_iter1;
wire    ap_block_state8_pp2_stage0_iter2;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln37_fu_541_p2;
reg   [0:0] icmp_ln37_reg_925;
reg   [0:0] icmp_ln37_reg_925_pp2_iter1_reg;
wire   [5:0] select_ln37_fu_559_p3;
reg   [5:0] select_ln37_reg_929;
wire   [8:0] select_ln37_1_fu_567_p3;
reg   [8:0] select_ln37_1_reg_935;
wire   [5:0] add_ln38_fu_575_p2;
wire   [13:0] add_ln40_1_fu_608_p2;
reg   [13:0] add_ln40_1_reg_947;
wire   [13:0] add_ln108_1_fu_644_p2;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_state13_pp3_stage0_iter0;
wire    ap_block_state14_pp3_stage0_iter1;
wire    ap_block_state15_pp3_stage0_iter2;
wire    ap_block_state16_pp3_stage0_iter3;
wire    ap_block_state17_pp3_stage0_iter4;
wire    ap_block_state18_pp3_stage0_iter5;
wire    ap_block_pp3_stage0_11001;
wire   [0:0] icmp_ln108_fu_650_p2;
reg   [0:0] icmp_ln108_reg_967;
reg   [0:0] icmp_ln108_reg_967_pp3_iter1_reg;
reg   [0:0] icmp_ln108_reg_967_pp3_iter2_reg;
reg   [0:0] icmp_ln108_reg_967_pp3_iter3_reg;
reg   [0:0] icmp_ln108_reg_967_pp3_iter4_reg;
wire   [5:0] select_ln108_fu_668_p3;
reg   [5:0] select_ln108_reg_971;
wire   [8:0] select_ln108_1_fu_676_p3;
reg   [8:0] select_ln108_1_reg_977;
wire   [5:0] add_ln109_fu_684_p2;
wire   [63:0] zext_ln110_2_fu_727_p1;
reg   [63:0] zext_ln110_2_reg_989;
reg   [63:0] zext_ln110_2_reg_989_pp3_iter2_reg;
reg   [63:0] zext_ln110_2_reg_989_pp3_iter3_reg;
reg   [63:0] zext_ln110_2_reg_989_pp3_iter4_reg;
wire   [31:0] mat_A_M_real_V_q0;
reg   [31:0] p_r_M_real_V_1_reg_1010;
reg    ap_enable_reg_pp3_iter2;
wire   [31:0] mat_A_M_imag_V_q0;
reg   [31:0] p_r_M_imag_V_2_reg_1015;
reg   [8:0] hamming_coeff_M_real_V_load_reg_1020;
wire   [39:0] zext_ln1118_fu_733_p1;
wire  signed [39:0] sext_ln1118_fu_736_p1;
wire  signed [39:0] sext_ln1118_1_fu_745_p1;
reg   [31:0] p_r_V_2_reg_1041;
reg   [31:0] p_r_M_imag_V_reg_1046;
wire   [13:0] add_ln59_1_fu_774_p2;
wire    ap_CS_fsm_pp4_stage0;
reg    ap_enable_reg_pp4_iter0;
wire    ap_block_state21_pp4_stage0_iter0;
wire    ap_block_state22_pp4_stage0_iter1;
wire    ap_block_state23_pp4_stage0_iter2;
wire    ap_block_pp4_stage0_11001;
wire   [0:0] icmp_ln59_fu_780_p2;
reg   [0:0] icmp_ln59_reg_1056;
reg   [0:0] icmp_ln59_reg_1056_pp4_iter1_reg;
wire   [5:0] select_ln59_fu_798_p3;
reg   [5:0] select_ln59_reg_1060;
wire   [8:0] select_ln59_1_fu_806_p3;
reg   [8:0] select_ln59_1_reg_1065;
wire   [5:0] add_ln60_fu_814_p2;
wire   [13:0] add_ln61_fu_859_p2;
reg   [13:0] add_ln61_reg_1087;
wire   [13:0] add_ln17_fu_870_p2;
reg    ap_enable_reg_pp5_iter0;
wire    ap_block_state25_pp5_stage0_iter0;
reg    ap_block_state26_pp5_stage0_iter1;
reg    ap_block_state26_io;
reg    ap_block_state27_pp5_stage0_iter2;
reg    ap_block_state27_io;
reg    ap_block_pp5_stage0_11001;
wire   [0:0] icmp_ln17_fu_876_p2;
wire   [31:0] real_V_q0;
wire   [13:0] add_ln21_fu_887_p2;
reg    ap_enable_reg_pp6_iter0;
wire    ap_block_state29_pp6_stage0_iter0;
reg    ap_block_state30_pp6_stage0_iter1;
reg    ap_block_state30_io;
reg    ap_block_state31_pp6_stage0_iter2;
reg    ap_block_state31_io;
reg    ap_block_pp6_stage0_11001;
wire   [0:0] icmp_ln21_fu_893_p2;
wire   [31:0] imag_V_q0;
wire    ap_CS_fsm_state5;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state6;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp2_iter2;
wire    ap_CS_fsm_state12;
wire    grp_matchedFilter_fu_467_ap_ready;
wire    grp_matchedFilter_fu_467_ap_done;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state13;
reg    ap_enable_reg_pp3_iter1;
reg    ap_enable_reg_pp3_iter3;
reg    ap_enable_reg_pp3_iter4;
reg    ap_enable_reg_pp3_iter5;
wire    ap_CS_fsm_state20;
wire    grp_fft_fu_479_ap_ready;
wire    grp_fft_fu_479_ap_done;
wire    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state21;
reg    ap_enable_reg_pp4_iter1;
reg    ap_enable_reg_pp4_iter2;
wire    ap_CS_fsm_state24;
reg    ap_block_pp5_stage0_subdone;
reg    ap_condition_pp5_exit_iter0_state25;
wire    ap_CS_fsm_state28;
reg    ap_block_pp6_stage0_subdone;
reg    ap_condition_pp6_exit_iter0_state29;
reg   [13:0] real_V_address0;
reg    real_V_ce0;
reg    real_V_we0;
reg   [31:0] real_V_d0;
reg   [13:0] imag_V_address0;
reg    imag_V_ce0;
reg    imag_V_we0;
reg   [31:0] imag_V_d0;
reg   [13:0] mat_A_M_real_V_address0;
reg    mat_A_M_real_V_ce0;
reg    mat_A_M_real_V_we0;
reg   [31:0] mat_A_M_real_V_d0;
reg   [13:0] mat_A_M_imag_V_address0;
reg    mat_A_M_imag_V_ce0;
reg    mat_A_M_imag_V_we0;
reg   [31:0] mat_A_M_imag_V_d0;
reg   [13:0] mat_B_M_real_V_address0;
reg    mat_B_M_real_V_ce0;
reg    mat_B_M_real_V_we0;
reg   [31:0] mat_B_M_real_V_d0;
wire   [31:0] mat_B_M_real_V_q0;
reg   [13:0] mat_B_M_imag_V_address0;
reg    mat_B_M_imag_V_ce0;
reg    mat_B_M_imag_V_we0;
reg   [31:0] mat_B_M_imag_V_d0;
wire   [31:0] mat_B_M_imag_V_q0;
wire    grp_matchedFilter_fu_467_ap_start;
wire    grp_matchedFilter_fu_467_ap_idle;
wire   [13:0] grp_matchedFilter_fu_467_a_M_real_address0;
wire    grp_matchedFilter_fu_467_a_M_real_ce0;
wire   [13:0] grp_matchedFilter_fu_467_a_M_imag_address0;
wire    grp_matchedFilter_fu_467_a_M_imag_ce0;
wire   [13:0] grp_matchedFilter_fu_467_out_M_real_address0;
wire    grp_matchedFilter_fu_467_out_M_real_ce0;
wire    grp_matchedFilter_fu_467_out_M_real_we0;
wire   [31:0] grp_matchedFilter_fu_467_out_M_real_d0;
wire   [13:0] grp_matchedFilter_fu_467_out_M_imag_address0;
wire    grp_matchedFilter_fu_467_out_M_imag_ce0;
wire    grp_matchedFilter_fu_467_out_M_imag_we0;
wire   [31:0] grp_matchedFilter_fu_467_out_M_imag_d0;
wire  signed [9:0] grp_matchedFilter_fu_467_grp_fu_739_p_din0;
wire  signed [31:0] grp_matchedFilter_fu_467_grp_fu_739_p_din1;
wire   [39:0] grp_matchedFilter_fu_467_grp_fu_739_p_dout0;
wire    grp_matchedFilter_fu_467_grp_fu_739_p_ce;
wire  signed [9:0] grp_matchedFilter_fu_467_grp_fu_748_p_din0;
wire  signed [31:0] grp_matchedFilter_fu_467_grp_fu_748_p_din1;
wire   [39:0] grp_matchedFilter_fu_467_grp_fu_748_p_dout0;
wire    grp_matchedFilter_fu_467_grp_fu_748_p_ce;
wire  signed [8:0] grp_matchedFilter_fu_467_grp_fu_1138_p_din0;
wire  signed [31:0] grp_matchedFilter_fu_467_grp_fu_1138_p_din1;
wire   [39:0] grp_matchedFilter_fu_467_grp_fu_1138_p_dout0;
wire    grp_matchedFilter_fu_467_grp_fu_1138_p_ce;
wire  signed [8:0] grp_matchedFilter_fu_467_grp_fu_1142_p_din0;
wire  signed [31:0] grp_matchedFilter_fu_467_grp_fu_1142_p_din1;
wire   [39:0] grp_matchedFilter_fu_467_grp_fu_1142_p_dout0;
wire    grp_matchedFilter_fu_467_grp_fu_1142_p_ce;
wire    grp_fft_fu_479_ap_start;
wire    grp_fft_fu_479_ap_idle;
wire   [13:0] grp_fft_fu_479_a_M_real_address0;
wire    grp_fft_fu_479_a_M_real_ce0;
wire   [13:0] grp_fft_fu_479_a_M_imag_address0;
wire    grp_fft_fu_479_a_M_imag_ce0;
wire   [13:0] grp_fft_fu_479_out_M_real_address0;
wire    grp_fft_fu_479_out_M_real_ce0;
wire    grp_fft_fu_479_out_M_real_we0;
wire   [31:0] grp_fft_fu_479_out_M_real_d0;
wire   [13:0] grp_fft_fu_479_out_M_imag_address0;
wire    grp_fft_fu_479_out_M_imag_ce0;
wire    grp_fft_fu_479_out_M_imag_we0;
wire   [31:0] grp_fft_fu_479_out_M_imag_d0;
wire  signed [9:0] grp_fft_fu_479_grp_fu_1130_p_din0;
wire  signed [31:0] grp_fft_fu_479_grp_fu_1130_p_din1;
wire   [39:0] grp_fft_fu_479_grp_fu_1130_p_dout0;
wire    grp_fft_fu_479_grp_fu_1130_p_ce;
wire  signed [9:0] grp_fft_fu_479_grp_fu_1134_p_din0;
wire  signed [31:0] grp_fft_fu_479_grp_fu_1134_p_din1;
wire   [39:0] grp_fft_fu_479_grp_fu_1134_p_dout0;
wire    grp_fft_fu_479_grp_fu_1134_p_ce;
wire  signed [9:0] grp_fft_fu_479_grp_fu_1146_p_din0;
wire  signed [31:0] grp_fft_fu_479_grp_fu_1146_p_din1;
wire   [39:0] grp_fft_fu_479_grp_fu_1146_p_dout0;
wire    grp_fft_fu_479_grp_fu_1146_p_ce;
wire  signed [9:0] grp_fft_fu_479_grp_fu_1150_p_din0;
wire  signed [31:0] grp_fft_fu_479_grp_fu_1150_p_din1;
wire   [39:0] grp_fft_fu_479_grp_fu_1150_p_dout0;
wire    grp_fft_fu_479_grp_fu_1150_p_ce;
wire    grp_matmul_fu_491_ap_start;
wire    grp_matmul_fu_491_ap_done;
wire    grp_matmul_fu_491_ap_idle;
wire    grp_matmul_fu_491_ap_ready;
wire   [13:0] grp_matmul_fu_491_a_M_real_address0;
wire    grp_matmul_fu_491_a_M_real_ce0;
wire   [13:0] grp_matmul_fu_491_a_M_imag_address0;
wire    grp_matmul_fu_491_a_M_imag_ce0;
wire   [13:0] grp_matmul_fu_491_out_M_real_address0;
wire    grp_matmul_fu_491_out_M_real_ce0;
wire    grp_matmul_fu_491_out_M_real_we0;
wire   [31:0] grp_matmul_fu_491_out_M_real_d0;
wire   [13:0] grp_matmul_fu_491_out_M_imag_address0;
wire    grp_matmul_fu_491_out_M_imag_ce0;
wire    grp_matmul_fu_491_out_M_imag_we0;
wire   [31:0] grp_matmul_fu_491_out_M_imag_d0;
wire  signed [9:0] grp_matmul_fu_491_grp_fu_1130_p_din0;
wire  signed [31:0] grp_matmul_fu_491_grp_fu_1130_p_din1;
wire   [39:0] grp_matmul_fu_491_grp_fu_1130_p_dout0;
wire    grp_matmul_fu_491_grp_fu_1130_p_ce;
wire  signed [9:0] grp_matmul_fu_491_grp_fu_1134_p_din0;
wire  signed [31:0] grp_matmul_fu_491_grp_fu_1134_p_din1;
wire   [39:0] grp_matmul_fu_491_grp_fu_1134_p_dout0;
wire    grp_matmul_fu_491_grp_fu_1134_p_ce;
reg   [13:0] i_reg_324;
wire    ap_CS_fsm_state1;
reg   [13:0] i_1_reg_335;
wire    ap_CS_fsm_state3;
reg   [8:0] ap_phi_mux_i_2_phi_fu_361_p4;
wire    ap_block_pp2_stage0;
reg   [8:0] ap_phi_mux_i_3_phi_fu_394_p4;
wire    ap_block_pp3_stage0;
reg   [8:0] ap_phi_mux_i_4_phi_fu_427_p4;
wire    ap_block_pp4_stage0;
reg    grp_matchedFilter_fu_467_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_fft_fu_479_ap_start_reg;
wire    ap_CS_fsm_state19;
reg    grp_matmul_fu_491_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [63:0] i_cast_fu_513_p1;
wire   [63:0] i_1_cast_fu_530_p1;
wire   [63:0] zext_ln40_fu_633_p1;
wire   [63:0] zext_ln40_3_fu_639_p1;
wire   [63:0] j_1_cast_fu_714_p1;
wire   [63:0] zext_ln62_3_fu_853_p1;
wire   [63:0] zext_ln62_fu_865_p1;
wire   [63:0] i_5_cast_fu_882_p1;
wire   [63:0] i_6_cast_fu_899_p1;
reg    ap_block_pp5_stage0_01001;
reg    ap_block_pp6_stage0_01001;
wire   [0:0] icmp_ln38_fu_553_p2;
wire   [8:0] add_ln37_fu_547_p2;
wire   [11:0] tmp_1_fu_588_p3;
wire   [13:0] tmp_fu_581_p3;
wire   [13:0] zext_ln40_1_fu_595_p1;
wire   [13:0] add_ln40_fu_599_p2;
wire   [13:0] zext_ln40_2_fu_605_p1;
wire   [11:0] j_cast_fu_614_p1;
wire   [11:0] add_ln39_1_fu_617_p2;
wire   [13:0] zext_ln39_fu_623_p1;
wire   [13:0] add_ln39_fu_627_p2;
wire   [0:0] icmp_ln109_fu_662_p2;
wire   [8:0] add_ln108_fu_656_p2;
wire   [11:0] tmp_3_fu_697_p3;
wire   [13:0] tmp_2_fu_690_p3;
wire   [13:0] zext_ln110_fu_704_p1;
wire   [13:0] add_ln110_fu_708_p2;
wire   [13:0] zext_ln110_1_fu_718_p1;
wire   [13:0] add_ln110_1_fu_721_p2;
reg  signed [9:0] grp_fu_739_p0;
reg  signed [31:0] grp_fu_739_p1;
reg  signed [9:0] grp_fu_748_p0;
reg  signed [31:0] grp_fu_748_p1;
wire   [39:0] grp_fu_739_p2;
wire   [39:0] grp_fu_748_p2;
wire   [0:0] icmp_ln60_fu_792_p2;
wire   [8:0] add_ln59_fu_786_p2;
wire   [11:0] tmp_5_fu_827_p3;
wire   [13:0] tmp_4_fu_820_p3;
wire   [13:0] zext_ln62_1_fu_834_p1;
wire   [13:0] add_ln62_fu_838_p2;
wire   [13:0] zext_ln62_2_fu_844_p1;
wire   [13:0] add_ln62_1_fu_847_p2;
reg    grp_fu_739_ce;
reg    grp_fu_748_ce;
wire   [39:0] grp_fu_1130_p2;
reg  signed [9:0] grp_fu_1130_p0;
reg  signed [31:0] grp_fu_1130_p1;
reg    grp_fu_1130_ce;
wire   [39:0] grp_fu_1134_p2;
reg  signed [9:0] grp_fu_1134_p0;
reg  signed [31:0] grp_fu_1134_p1;
reg    grp_fu_1134_ce;
wire   [39:0] grp_fu_1138_p2;
wire  signed [8:0] grp_fu_1138_p0;
wire  signed [31:0] grp_fu_1138_p1;
reg    grp_fu_1138_ce;
wire   [39:0] grp_fu_1142_p2;
wire  signed [8:0] grp_fu_1142_p0;
wire  signed [31:0] grp_fu_1142_p1;
reg    grp_fu_1142_ce;
wire   [39:0] grp_fu_1146_p2;
wire  signed [9:0] grp_fu_1146_p0;
wire  signed [31:0] grp_fu_1146_p1;
reg    grp_fu_1146_ce;
wire   [39:0] grp_fu_1150_p2;
wire  signed [9:0] grp_fu_1150_p0;
wire  signed [31:0] grp_fu_1150_p1;
reg    grp_fu_1150_ce;
reg   [18:0] ap_NS_fsm;
wire    ap_CS_fsm_state32;
wire    regslice_both_data_OUT_U_apdone_blk;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
reg    ap_idle_pp5;
wire    ap_enable_pp5;
reg    ap_idle_pp6;
wire    ap_enable_pp6;
wire    regslice_both_data_IN_U_apdone_blk;
wire   [31:0] data_IN_TDATA_int_regslice;
wire    data_IN_TVALID_int_regslice;
reg    data_IN_TREADY_int_regslice;
wire    regslice_both_data_IN_U_ack_in;
reg   [31:0] data_OUT_TDATA_int_regslice;
reg    data_OUT_TVALID_int_regslice;
wire    data_OUT_TREADY_int_regslice;
wire    regslice_both_data_OUT_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 ap_enable_reg_pp5_iter1 = 1'b0;
#0 ap_enable_reg_pp5_iter2 = 1'b0;
#0 ap_enable_reg_pp6_iter1 = 1'b0;
#0 ap_enable_reg_pp6_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter0 = 1'b0;
#0 ap_enable_reg_pp6_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_enable_reg_pp3_iter5 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter2 = 1'b0;
#0 grp_matchedFilter_fu_467_ap_start_reg = 1'b0;
#0 grp_fft_fu_479_ap_start_reg = 1'b0;
#0 grp_matmul_fu_491_ap_start_reg = 1'b0;
end

top_hamming_coeff_M_real_V #(
    .DataWidth( 9 ),
    .AddressRange( 39 ),
    .AddressWidth( 6 ))
hamming_coeff_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hamming_coeff_M_real_V_address0),
    .ce0(hamming_coeff_M_real_V_ce0),
    .q0(hamming_coeff_M_real_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(real_V_address0),
    .ce0(real_V_ce0),
    .we0(real_V_we0),
    .d0(real_V_d0),
    .q0(real_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(imag_V_address0),
    .ce0(imag_V_ce0),
    .we0(imag_V_we0),
    .d0(imag_V_d0),
    .q0(imag_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
mat_A_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_M_real_V_address0),
    .ce0(mat_A_M_real_V_ce0),
    .we0(mat_A_M_real_V_we0),
    .d0(mat_A_M_real_V_d0),
    .q0(mat_A_M_real_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
mat_A_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_M_imag_V_address0),
    .ce0(mat_A_M_imag_V_ce0),
    .we0(mat_A_M_imag_V_we0),
    .d0(mat_A_M_imag_V_d0),
    .q0(mat_A_M_imag_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
mat_B_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_B_M_real_V_address0),
    .ce0(mat_B_M_real_V_ce0),
    .we0(mat_B_M_real_V_we0),
    .d0(mat_B_M_real_V_d0),
    .q0(mat_B_M_real_V_q0)
);

top_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 12520 ),
    .AddressWidth( 14 ))
mat_B_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_B_M_imag_V_address0),
    .ce0(mat_B_M_imag_V_ce0),
    .we0(mat_B_M_imag_V_we0),
    .d0(mat_B_M_imag_V_d0),
    .q0(mat_B_M_imag_V_q0)
);

top_matchedFilter grp_matchedFilter_fu_467(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matchedFilter_fu_467_ap_start),
    .ap_done(grp_matchedFilter_fu_467_ap_done),
    .ap_idle(grp_matchedFilter_fu_467_ap_idle),
    .ap_ready(grp_matchedFilter_fu_467_ap_ready),
    .a_M_real_address0(grp_matchedFilter_fu_467_a_M_real_address0),
    .a_M_real_ce0(grp_matchedFilter_fu_467_a_M_real_ce0),
    .a_M_real_q0(mat_B_M_real_V_q0),
    .a_M_imag_address0(grp_matchedFilter_fu_467_a_M_imag_address0),
    .a_M_imag_ce0(grp_matchedFilter_fu_467_a_M_imag_ce0),
    .a_M_imag_q0(mat_B_M_imag_V_q0),
    .out_M_real_address0(grp_matchedFilter_fu_467_out_M_real_address0),
    .out_M_real_ce0(grp_matchedFilter_fu_467_out_M_real_ce0),
    .out_M_real_we0(grp_matchedFilter_fu_467_out_M_real_we0),
    .out_M_real_d0(grp_matchedFilter_fu_467_out_M_real_d0),
    .out_M_imag_address0(grp_matchedFilter_fu_467_out_M_imag_address0),
    .out_M_imag_ce0(grp_matchedFilter_fu_467_out_M_imag_ce0),
    .out_M_imag_we0(grp_matchedFilter_fu_467_out_M_imag_we0),
    .out_M_imag_d0(grp_matchedFilter_fu_467_out_M_imag_d0),
    .grp_fu_739_p_din0(grp_matchedFilter_fu_467_grp_fu_739_p_din0),
    .grp_fu_739_p_din1(grp_matchedFilter_fu_467_grp_fu_739_p_din1),
    .grp_fu_739_p_dout0(grp_matchedFilter_fu_467_grp_fu_739_p_dout0),
    .grp_fu_739_p_ce(grp_matchedFilter_fu_467_grp_fu_739_p_ce),
    .grp_fu_748_p_din0(grp_matchedFilter_fu_467_grp_fu_748_p_din0),
    .grp_fu_748_p_din1(grp_matchedFilter_fu_467_grp_fu_748_p_din1),
    .grp_fu_748_p_dout0(grp_matchedFilter_fu_467_grp_fu_748_p_dout0),
    .grp_fu_748_p_ce(grp_matchedFilter_fu_467_grp_fu_748_p_ce),
    .grp_fu_1138_p_din0(grp_matchedFilter_fu_467_grp_fu_1138_p_din0),
    .grp_fu_1138_p_din1(grp_matchedFilter_fu_467_grp_fu_1138_p_din1),
    .grp_fu_1138_p_dout0(grp_matchedFilter_fu_467_grp_fu_1138_p_dout0),
    .grp_fu_1138_p_ce(grp_matchedFilter_fu_467_grp_fu_1138_p_ce),
    .grp_fu_1142_p_din0(grp_matchedFilter_fu_467_grp_fu_1142_p_din0),
    .grp_fu_1142_p_din1(grp_matchedFilter_fu_467_grp_fu_1142_p_din1),
    .grp_fu_1142_p_dout0(grp_matchedFilter_fu_467_grp_fu_1142_p_dout0),
    .grp_fu_1142_p_ce(grp_matchedFilter_fu_467_grp_fu_1142_p_ce)
);

top_fft grp_fft_fu_479(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fft_fu_479_ap_start),
    .ap_done(grp_fft_fu_479_ap_done),
    .ap_idle(grp_fft_fu_479_ap_idle),
    .ap_ready(grp_fft_fu_479_ap_ready),
    .a_M_real_address0(grp_fft_fu_479_a_M_real_address0),
    .a_M_real_ce0(grp_fft_fu_479_a_M_real_ce0),
    .a_M_real_q0(mat_B_M_real_V_q0),
    .a_M_imag_address0(grp_fft_fu_479_a_M_imag_address0),
    .a_M_imag_ce0(grp_fft_fu_479_a_M_imag_ce0),
    .a_M_imag_q0(mat_B_M_imag_V_q0),
    .out_M_real_address0(grp_fft_fu_479_out_M_real_address0),
    .out_M_real_ce0(grp_fft_fu_479_out_M_real_ce0),
    .out_M_real_we0(grp_fft_fu_479_out_M_real_we0),
    .out_M_real_d0(grp_fft_fu_479_out_M_real_d0),
    .out_M_imag_address0(grp_fft_fu_479_out_M_imag_address0),
    .out_M_imag_ce0(grp_fft_fu_479_out_M_imag_ce0),
    .out_M_imag_we0(grp_fft_fu_479_out_M_imag_we0),
    .out_M_imag_d0(grp_fft_fu_479_out_M_imag_d0),
    .grp_fu_1130_p_din0(grp_fft_fu_479_grp_fu_1130_p_din0),
    .grp_fu_1130_p_din1(grp_fft_fu_479_grp_fu_1130_p_din1),
    .grp_fu_1130_p_dout0(grp_fft_fu_479_grp_fu_1130_p_dout0),
    .grp_fu_1130_p_ce(grp_fft_fu_479_grp_fu_1130_p_ce),
    .grp_fu_1134_p_din0(grp_fft_fu_479_grp_fu_1134_p_din0),
    .grp_fu_1134_p_din1(grp_fft_fu_479_grp_fu_1134_p_din1),
    .grp_fu_1134_p_dout0(grp_fft_fu_479_grp_fu_1134_p_dout0),
    .grp_fu_1134_p_ce(grp_fft_fu_479_grp_fu_1134_p_ce),
    .grp_fu_1146_p_din0(grp_fft_fu_479_grp_fu_1146_p_din0),
    .grp_fu_1146_p_din1(grp_fft_fu_479_grp_fu_1146_p_din1),
    .grp_fu_1146_p_dout0(grp_fft_fu_479_grp_fu_1146_p_dout0),
    .grp_fu_1146_p_ce(grp_fft_fu_479_grp_fu_1146_p_ce),
    .grp_fu_1150_p_din0(grp_fft_fu_479_grp_fu_1150_p_din0),
    .grp_fu_1150_p_din1(grp_fft_fu_479_grp_fu_1150_p_din1),
    .grp_fu_1150_p_dout0(grp_fft_fu_479_grp_fu_1150_p_dout0),
    .grp_fu_1150_p_ce(grp_fft_fu_479_grp_fu_1150_p_ce)
);

top_matmul grp_matmul_fu_491(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_fu_491_ap_start),
    .ap_done(grp_matmul_fu_491_ap_done),
    .ap_idle(grp_matmul_fu_491_ap_idle),
    .ap_ready(grp_matmul_fu_491_ap_ready),
    .a_M_real_address0(grp_matmul_fu_491_a_M_real_address0),
    .a_M_real_ce0(grp_matmul_fu_491_a_M_real_ce0),
    .a_M_real_q0(mat_A_M_real_V_q0),
    .a_M_imag_address0(grp_matmul_fu_491_a_M_imag_address0),
    .a_M_imag_ce0(grp_matmul_fu_491_a_M_imag_ce0),
    .a_M_imag_q0(mat_A_M_imag_V_q0),
    .out_M_real_address0(grp_matmul_fu_491_out_M_real_address0),
    .out_M_real_ce0(grp_matmul_fu_491_out_M_real_ce0),
    .out_M_real_we0(grp_matmul_fu_491_out_M_real_we0),
    .out_M_real_d0(grp_matmul_fu_491_out_M_real_d0),
    .out_M_imag_address0(grp_matmul_fu_491_out_M_imag_address0),
    .out_M_imag_ce0(grp_matmul_fu_491_out_M_imag_ce0),
    .out_M_imag_we0(grp_matmul_fu_491_out_M_imag_we0),
    .out_M_imag_d0(grp_matmul_fu_491_out_M_imag_d0),
    .grp_fu_1130_p_din0(grp_matmul_fu_491_grp_fu_1130_p_din0),
    .grp_fu_1130_p_din1(grp_matmul_fu_491_grp_fu_1130_p_din1),
    .grp_fu_1130_p_dout0(grp_matmul_fu_491_grp_fu_1130_p_dout0),
    .grp_fu_1130_p_ce(grp_matmul_fu_491_grp_fu_1130_p_ce),
    .grp_fu_1134_p_din0(grp_matmul_fu_491_grp_fu_1134_p_din0),
    .grp_fu_1134_p_din1(grp_matmul_fu_491_grp_fu_1134_p_din1),
    .grp_fu_1134_p_dout0(grp_matmul_fu_491_grp_fu_1134_p_dout0),
    .grp_fu_1134_p_ce(grp_matmul_fu_491_grp_fu_1134_p_ce)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U33(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_739_p0),
    .din1(grp_fu_739_p1),
    .ce(grp_fu_739_ce),
    .dout(grp_fu_739_p2)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_748_p0),
    .din1(grp_fu_748_p1),
    .ce(grp_fu_748_ce),
    .dout(grp_fu_748_p2)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1130_p0),
    .din1(grp_fu_1130_p1),
    .ce(grp_fu_1130_ce),
    .dout(grp_fu_1130_p2)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1134_p0),
    .din1(grp_fu_1134_p1),
    .ce(grp_fu_1134_ce),
    .dout(grp_fu_1134_p2)
);

top_mul_9s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_9s_32s_40_2_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1138_p0),
    .din1(grp_fu_1138_p1),
    .ce(grp_fu_1138_ce),
    .dout(grp_fu_1138_p2)
);

top_mul_9s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_9s_32s_40_2_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1142_p0),
    .din1(grp_fu_1142_p1),
    .ce(grp_fu_1142_ce),
    .dout(grp_fu_1142_p2)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1146_p0),
    .din1(grp_fu_1146_p1),
    .ce(grp_fu_1146_ce),
    .dout(grp_fu_1146_p2)
);

top_mul_10s_32s_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_10s_32s_40_2_1_U40(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1150_p0),
    .din1(grp_fu_1150_p1),
    .ce(grp_fu_1150_ce),
    .dout(grp_fu_1150_p2)
);

top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_data_IN_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_IN_TDATA),
    .vld_in(data_IN_TVALID),
    .ack_in(regslice_both_data_IN_U_ack_in),
    .data_out(data_IN_TDATA_int_regslice),
    .vld_out(data_IN_TVALID_int_regslice),
    .ack_out(data_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_IN_U_apdone_blk)
);

top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_data_OUT_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_OUT_TDATA_int_regslice),
    .vld_in(data_OUT_TVALID_int_regslice),
    .ack_in(data_OUT_TREADY_int_regslice),
    .data_out(data_OUT_TDATA),
    .vld_out(regslice_both_data_OUT_U_vld_out),
    .ack_out(data_OUT_TREADY),
    .apdone_blk(regslice_both_data_OUT_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state6)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state6);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state13) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state13)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state13);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
        end else if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
            ap_enable_reg_pp3_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state21) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp4_exit_iter0_state21)) begin
                ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state21);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter2 <= ap_enable_reg_pp4_iter1;
        end else if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
            ap_enable_reg_pp4_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp5_stage0_subdone) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b1 == ap_condition_pp5_exit_iter0_state25))) begin
            ap_enable_reg_pp5_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            ap_enable_reg_pp5_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp5_exit_iter0_state25)) begin
                ap_enable_reg_pp5_iter1 <= (1'b1 ^ ap_condition_pp5_exit_iter0_state25);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp5_iter1 <= ap_enable_reg_pp5_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp5_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter2 <= ap_enable_reg_pp5_iter1;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            ap_enable_reg_pp5_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp6_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp6_stage0_subdone) & (1'b1 == ap_CS_fsm_pp6_stage0) & (1'b1 == ap_condition_pp6_exit_iter0_state29))) begin
            ap_enable_reg_pp6_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state28)) begin
            ap_enable_reg_pp6_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp6_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp6_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp6_exit_iter0_state29)) begin
                ap_enable_reg_pp6_iter1 <= (1'b1 ^ ap_condition_pp6_exit_iter0_state29);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp6_iter1 <= ap_enable_reg_pp6_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp6_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp6_stage0_subdone)) begin
            ap_enable_reg_pp6_iter2 <= ap_enable_reg_pp6_iter1;
        end else if ((1'b1 == ap_CS_fsm_state28)) begin
            ap_enable_reg_pp6_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fft_fu_479_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_fft_fu_479_ap_start_reg <= 1'b1;
        end else if ((grp_fft_fu_479_ap_ready == 1'b1)) begin
            grp_fft_fu_479_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matchedFilter_fu_467_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_matchedFilter_fu_467_ap_start_reg <= 1'b1;
        end else if ((grp_matchedFilter_fu_467_ap_ready == 1'b1)) begin
            grp_matchedFilter_fu_467_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_fu_491_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_matmul_fu_491_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_fu_491_ap_ready == 1'b1)) begin
            grp_matmul_fu_491_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_335 <= 14'd0;
    end else if ((~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln10_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_1_reg_335 <= add_ln10_fu_518_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_2_reg_357 <= 9'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_reg_925 == 1'd0))) begin
        i_2_reg_357 <= select_ln37_1_reg_935;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln108_reg_967 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        i_3_reg_390 <= select_ln108_1_reg_977;
    end else if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        i_3_reg_390 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (icmp_ln59_reg_1056 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        i_4_reg_423 <= select_ln59_1_reg_1065;
    end else if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        i_4_reg_423 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        i_5_reg_445 <= 14'd0;
    end else if (((1'b0 == ap_block_pp5_stage0_11001) & (icmp_ln17_fu_876_p2 == 1'd0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        i_5_reg_445 <= add_ln17_fu_870_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        i_6_reg_456 <= 14'd0;
    end else if (((1'b0 == ap_block_pp6_stage0_11001) & (icmp_ln21_fu_893_p2 == 1'd0) & (ap_enable_reg_pp6_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp6_stage0))) begin
        i_6_reg_456 <= add_ln21_fu_887_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_reg_324 <= 14'd0;
    end else if ((~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln6_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_324 <= add_ln6_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln59_fu_780_p2 == 1'd0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        indvar_flatten15_reg_412 <= add_ln59_1_fu_774_p2;
    end else if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        indvar_flatten15_reg_412 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_fu_650_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        indvar_flatten7_reg_379 <= add_ln108_1_fu_644_p2;
    end else if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        indvar_flatten7_reg_379 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        indvar_flatten_reg_346 <= 14'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_541_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        indvar_flatten_reg_346 <= add_ln37_1_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_fu_650_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        j_1_reg_401 <= add_ln109_fu_684_p2;
    end else if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        j_1_reg_401 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln59_fu_780_p2 == 1'd0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        j_2_reg_434 <= add_ln60_fu_814_p2;
    end else if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        j_2_reg_434 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_368 <= 6'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_541_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        j_reg_368 <= add_ln38_fu_575_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_reg_925 == 1'd0))) begin
        add_ln40_1_reg_947 <= add_ln40_1_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln59_reg_1056 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        add_ln61_reg_1087 <= add_ln61_fu_859_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_reg_967_pp3_iter1_reg == 1'd0))) begin
        hamming_coeff_M_real_V_load_reg_1020 <= hamming_coeff_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln108_reg_967 <= icmp_ln108_fu_650_p2;
        icmp_ln108_reg_967_pp3_iter1_reg <= icmp_ln108_reg_967;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp3_stage0_11001)) begin
        icmp_ln108_reg_967_pp3_iter2_reg <= icmp_ln108_reg_967_pp3_iter1_reg;
        icmp_ln108_reg_967_pp3_iter3_reg <= icmp_ln108_reg_967_pp3_iter2_reg;
        icmp_ln108_reg_967_pp3_iter4_reg <= icmp_ln108_reg_967_pp3_iter3_reg;
        zext_ln110_2_reg_989_pp3_iter2_reg[13 : 0] <= zext_ln110_2_reg_989[13 : 0];
        zext_ln110_2_reg_989_pp3_iter3_reg[13 : 0] <= zext_ln110_2_reg_989_pp3_iter2_reg[13 : 0];
        zext_ln110_2_reg_989_pp3_iter4_reg[13 : 0] <= zext_ln110_2_reg_989_pp3_iter3_reg[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp5_stage0_11001) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        icmp_ln17_reg_1097 <= icmp_ln17_fu_876_p2;
        icmp_ln17_reg_1097_pp5_iter1_reg <= icmp_ln17_reg_1097;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp6_stage0_11001) & (1'b1 == ap_CS_fsm_pp6_stage0))) begin
        icmp_ln21_reg_1116 <= icmp_ln21_fu_893_p2;
        icmp_ln21_reg_1116_pp6_iter1_reg <= icmp_ln21_reg_1116;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln37_reg_925 <= icmp_ln37_fu_541_p2;
        icmp_ln37_reg_925_pp2_iter1_reg <= icmp_ln37_reg_925;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        icmp_ln59_reg_1056 <= icmp_ln59_fu_780_p2;
        icmp_ln59_reg_1056_pp4_iter1_reg <= icmp_ln59_reg_1056;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln108_reg_967_pp3_iter1_reg == 1'd0))) begin
        p_r_M_imag_V_2_reg_1015 <= mat_A_M_imag_V_q0;
        p_r_M_real_V_1_reg_1010 <= mat_A_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_reg_967_pp3_iter3_reg == 1'd0))) begin
        p_r_M_imag_V_reg_1046 <= {{grp_fu_748_p2[39:8]}};
        p_r_V_2_reg_1041 <= {{grp_fu_739_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_fu_650_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        select_ln108_1_reg_977 <= select_ln108_1_fu_676_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_fu_650_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        select_ln108_reg_971 <= select_ln108_fu_668_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_541_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        select_ln37_1_reg_935 <= select_ln37_1_fu_567_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_fu_541_p2 == 1'd0))) begin
        select_ln37_reg_929 <= select_ln37_fu_559_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln59_fu_780_p2 == 1'd0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        select_ln59_1_reg_1065 <= select_ln59_1_fu_806_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln59_fu_780_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        select_ln59_reg_1060 <= select_ln59_fu_798_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln108_reg_967 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        zext_ln110_2_reg_989[13 : 0] <= zext_ln110_2_fu_727_p1[13 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln37_fu_541_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln108_fu_650_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state13 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state13 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln59_fu_780_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state21 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state21 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln17_fu_876_p2 == 1'd1)) begin
        ap_condition_pp5_exit_iter0_state25 = 1'b1;
    end else begin
        ap_condition_pp5_exit_iter0_state25 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln21_fu_893_p2 == 1'd1)) begin
        ap_condition_pp6_exit_iter0_state29 = 1'b1;
    end else begin
        ap_condition_pp6_exit_iter0_state29 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter5 == 1'b0) & (ap_enable_reg_pp3_iter4 == 1'b0) & (ap_enable_reg_pp3_iter3 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter2 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b0) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter0 == 1'b0))) begin
        ap_idle_pp5 = 1'b1;
    end else begin
        ap_idle_pp5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp6_iter1 == 1'b0) & (ap_enable_reg_pp6_iter0 == 1'b0) & (ap_enable_reg_pp6_iter2 == 1'b0))) begin
        ap_idle_pp6 = 1'b1;
    end else begin
        ap_idle_pp6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln37_reg_925 == 1'd0))) begin
        ap_phi_mux_i_2_phi_fu_361_p4 = select_ln37_1_reg_935;
    end else begin
        ap_phi_mux_i_2_phi_fu_361_p4 = i_2_reg_357;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln108_reg_967 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_i_3_phi_fu_394_p4 = select_ln108_1_reg_977;
    end else begin
        ap_phi_mux_i_3_phi_fu_394_p4 = i_3_reg_390;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (icmp_ln59_reg_1056 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        ap_phi_mux_i_4_phi_fu_427_p4 = select_ln59_1_reg_1065;
    end else begin
        ap_phi_mux_i_4_phi_fu_427_p4 = i_4_reg_423;
    end
end

always @ (*) begin
    if ((((icmp_ln10_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln6_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        data_IN_TDATA_blk_n = data_IN_TVALID_int_regslice;
    end else begin
        data_IN_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln6_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln10_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        data_IN_TREADY_int_regslice = 1'b1;
    end else begin
        data_IN_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln21_reg_1116 == 1'd0) & (ap_enable_reg_pp6_iter1 == 1'b1) & (1'b0 == ap_block_pp6_stage0) & (1'b1 == ap_CS_fsm_pp6_stage0)) | ((1'b0 == ap_block_pp6_stage0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0) & (ap_enable_reg_pp6_iter2 == 1'b1)) | ((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (ap_enable_reg_pp5_iter2 == 1'b1) & (1'b0 == ap_block_pp5_stage0)) | ((icmp_ln17_reg_1097 == 1'd0) & (1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)))) begin
        data_OUT_TDATA_blk_n = data_OUT_TREADY_int_regslice;
    end else begin
        data_OUT_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln21_reg_1116 == 1'd0) & (ap_enable_reg_pp6_iter1 == 1'b1) & (1'b0 == ap_block_pp6_stage0_01001) & (1'b1 == ap_CS_fsm_pp6_stage0))) begin
        data_OUT_TDATA_int_regslice = imag_V_q0;
    end else if (((icmp_ln17_reg_1097 == 1'd0) & (1'b0 == ap_block_pp5_stage0_01001) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        data_OUT_TDATA_int_regslice = real_V_q0;
    end else begin
        data_OUT_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln21_reg_1116 == 1'd0) & (ap_enable_reg_pp6_iter1 == 1'b1) & (1'b0 == ap_block_pp6_stage0_11001) & (1'b1 == ap_CS_fsm_pp6_stage0)) | ((icmp_ln17_reg_1097 == 1'd0) & (1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)))) begin
        data_OUT_TVALID_int_regslice = 1'b1;
    end else begin
        data_OUT_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1130_ce = grp_matmul_fu_491_grp_fu_1130_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1130_ce = grp_fft_fu_479_grp_fu_1130_p_ce;
    end else begin
        grp_fu_1130_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1130_p0 = grp_matmul_fu_491_grp_fu_1130_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1130_p0 = grp_fft_fu_479_grp_fu_1130_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1130_p1 = grp_matmul_fu_491_grp_fu_1130_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1130_p1 = grp_fft_fu_479_grp_fu_1130_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1134_ce = grp_matmul_fu_491_grp_fu_1134_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1134_ce = grp_fft_fu_479_grp_fu_1134_p_ce;
    end else begin
        grp_fu_1134_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1134_p0 = grp_matmul_fu_491_grp_fu_1134_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1134_p0 = grp_fft_fu_479_grp_fu_1134_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_1134_p1 = grp_matmul_fu_491_grp_fu_1134_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1134_p1 = grp_fft_fu_479_grp_fu_1134_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_1138_ce = grp_matchedFilter_fu_467_grp_fu_1138_p_ce;
    end else begin
        grp_fu_1138_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_1142_ce = grp_matchedFilter_fu_467_grp_fu_1142_p_ce;
    end else begin
        grp_fu_1142_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1146_ce = grp_fft_fu_479_grp_fu_1146_p_ce;
    end else begin
        grp_fu_1146_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_1150_ce = grp_fft_fu_479_grp_fu_1150_p_ce;
    end else begin
        grp_fu_1150_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_739_ce = grp_matchedFilter_fu_467_grp_fu_739_p_ce;
    end else begin
        grp_fu_739_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_739_p0 = grp_matchedFilter_fu_467_grp_fu_739_p_din0;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        grp_fu_739_p0 = zext_ln1118_fu_733_p1;
    end else begin
        grp_fu_739_p0 = zext_ln1118_fu_733_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_739_p1 = grp_matchedFilter_fu_467_grp_fu_739_p_din1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        grp_fu_739_p1 = sext_ln1118_fu_736_p1;
    end else begin
        grp_fu_739_p1 = sext_ln1118_fu_736_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_748_ce = grp_matchedFilter_fu_467_grp_fu_748_p_ce;
    end else begin
        grp_fu_748_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_748_p0 = grp_matchedFilter_fu_467_grp_fu_748_p_din0;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        grp_fu_748_p0 = zext_ln1118_fu_733_p1;
    end else begin
        grp_fu_748_p0 = zext_ln1118_fu_733_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_748_p1 = grp_matchedFilter_fu_467_grp_fu_748_p_din1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        grp_fu_748_p1 = sext_ln1118_1_fu_745_p1;
    end else begin
        grp_fu_748_p1 = sext_ln1118_1_fu_745_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        hamming_coeff_M_real_V_ce0 = 1'b1;
    end else begin
        hamming_coeff_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp6_stage0) & (ap_enable_reg_pp6_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp6_stage0))) begin
        imag_V_address0 = i_6_cast_fu_899_p1;
    end else if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter2 == 1'b1))) begin
        imag_V_address0 = zext_ln62_fu_865_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        imag_V_address0 = zext_ln40_fu_633_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        imag_V_address0 = i_1_cast_fu_530_p1;
    end else begin
        imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp6_stage0_11001) & (ap_enable_reg_pp6_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp6_stage0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter2 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        imag_V_ce0 = 1'b1;
    end else begin
        imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter2 == 1'b1))) begin
        imag_V_d0 = mat_A_M_imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        imag_V_d0 = data_IN_TDATA_int_regslice;
    end else begin
        imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter2 == 1'b1) & (icmp_ln59_reg_1056_pp4_iter1_reg == 1'd0)) | (~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln10_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        imag_V_we0 = 1'b1;
    end else begin
        imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        mat_A_M_imag_V_address0 = zext_ln62_3_fu_853_p1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        mat_A_M_imag_V_address0 = zext_ln110_2_fu_727_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        mat_A_M_imag_V_address0 = zext_ln40_3_fu_639_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_A_M_imag_V_address0 = grp_matmul_fu_491_a_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_imag_V_address0 = grp_fft_fu_479_out_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_imag_V_address0 = grp_matchedFilter_fu_467_out_M_imag_address0;
    end else begin
        mat_A_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1)))) begin
        mat_A_M_imag_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_A_M_imag_V_ce0 = grp_matmul_fu_491_a_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_imag_V_ce0 = grp_fft_fu_479_out_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_imag_V_ce0 = grp_matchedFilter_fu_467_out_M_imag_ce0;
    end else begin
        mat_A_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        mat_A_M_imag_V_d0 = imag_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_imag_V_d0 = grp_fft_fu_479_out_M_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_imag_V_d0 = grp_matchedFilter_fu_467_out_M_imag_d0;
    end else begin
        mat_A_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (icmp_ln37_reg_925_pp2_iter1_reg == 1'd0))) begin
        mat_A_M_imag_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_imag_V_we0 = grp_fft_fu_479_out_M_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_imag_V_we0 = grp_matchedFilter_fu_467_out_M_imag_we0;
    end else begin
        mat_A_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        mat_A_M_real_V_address0 = zext_ln62_3_fu_853_p1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        mat_A_M_real_V_address0 = zext_ln110_2_fu_727_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        mat_A_M_real_V_address0 = zext_ln40_3_fu_639_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_A_M_real_V_address0 = grp_matmul_fu_491_a_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_real_V_address0 = grp_fft_fu_479_out_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_real_V_address0 = grp_matchedFilter_fu_467_out_M_real_address0;
    end else begin
        mat_A_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1)))) begin
        mat_A_M_real_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_A_M_real_V_ce0 = grp_matmul_fu_491_a_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_real_V_ce0 = grp_fft_fu_479_out_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_real_V_ce0 = grp_matchedFilter_fu_467_out_M_real_ce0;
    end else begin
        mat_A_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        mat_A_M_real_V_d0 = real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_real_V_d0 = grp_fft_fu_479_out_M_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_real_V_d0 = grp_matchedFilter_fu_467_out_M_real_d0;
    end else begin
        mat_A_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (icmp_ln37_reg_925_pp2_iter1_reg == 1'd0))) begin
        mat_A_M_real_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_A_M_real_V_we0 = grp_fft_fu_479_out_M_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_A_M_real_V_we0 = grp_matchedFilter_fu_467_out_M_real_we0;
    end else begin
        mat_A_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_imag_V_address0 = zext_ln110_2_reg_989_pp3_iter4_reg;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_imag_V_address0 = grp_matmul_fu_491_out_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_B_M_imag_V_address0 = grp_fft_fu_479_a_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_B_M_imag_V_address0 = grp_matchedFilter_fu_467_a_M_imag_address0;
    end else begin
        mat_B_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_imag_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_imag_V_ce0 = grp_matmul_fu_491_out_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_B_M_imag_V_ce0 = grp_fft_fu_479_a_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_B_M_imag_V_ce0 = grp_matchedFilter_fu_467_a_M_imag_ce0;
    end else begin
        mat_B_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_imag_V_d0 = p_r_M_imag_V_reg_1046;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_imag_V_d0 = grp_matmul_fu_491_out_M_imag_d0;
    end else begin
        mat_B_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln108_reg_967_pp3_iter4_reg == 1'd0))) begin
        mat_B_M_imag_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_imag_V_we0 = grp_matmul_fu_491_out_M_imag_we0;
    end else begin
        mat_B_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_real_V_address0 = zext_ln110_2_reg_989_pp3_iter4_reg;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_real_V_address0 = grp_matmul_fu_491_out_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_B_M_real_V_address0 = grp_fft_fu_479_a_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_B_M_real_V_address0 = grp_matchedFilter_fu_467_a_M_real_address0;
    end else begin
        mat_B_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_real_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_real_V_ce0 = grp_matmul_fu_491_out_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mat_B_M_real_V_ce0 = grp_fft_fu_479_a_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mat_B_M_real_V_ce0 = grp_matchedFilter_fu_467_a_M_real_ce0;
    end else begin
        mat_B_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        mat_B_M_real_V_d0 = p_r_V_2_reg_1041;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_real_V_d0 = grp_matmul_fu_491_out_M_real_d0;
    end else begin
        mat_B_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln108_reg_967_pp3_iter4_reg == 1'd0))) begin
        mat_B_M_real_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mat_B_M_real_V_we0 = grp_matmul_fu_491_out_M_real_we0;
    end else begin
        mat_B_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp5_stage0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0))) begin
        real_V_address0 = i_5_cast_fu_882_p1;
    end else if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter2 == 1'b1))) begin
        real_V_address0 = zext_ln62_fu_865_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        real_V_address0 = zext_ln40_fu_633_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        real_V_address0 = i_cast_fu_513_p1;
    end else begin
        real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp5_stage0_11001) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0)) | ((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter2 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        real_V_ce0 = 1'b1;
    end else begin
        real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter2 == 1'b1))) begin
        real_V_d0 = mat_A_M_real_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        real_V_d0 = data_IN_TDATA_int_regslice;
    end else begin
        real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter2 == 1'b1) & (icmp_ln59_reg_1056_pp4_iter1_reg == 1'd0)) | (~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln6_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        real_V_we0 = 1'b1;
    end else begin
        real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln6_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln6_fu_507_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln10_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0)) & (icmp_ln10_fu_524_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln37_fu_541_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter2 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter2 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln37_fu_541_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_matmul_fu_491_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_matchedFilter_fu_467_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln108_fu_650_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0)) | ((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln108_fu_650_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_fft_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_pp4_stage0 : begin
            if ((~((1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter1 == 1'b0) & (icmp_ln59_fu_780_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter2 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if ((((1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter2 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0)) | ((1'b0 == ap_block_pp4_stage0_subdone) & (ap_enable_reg_pp4_iter1 == 1'b0) & (icmp_ln59_fu_780_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_pp5_stage0;
        end
        ap_ST_fsm_pp5_stage0 : begin
            if ((~((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln17_fu_876_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1)) & ~((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end else if ((((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0)) | ((1'b0 == ap_block_pp5_stage0_subdone) & (ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln17_fu_876_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_pp6_stage0;
        end
        ap_ST_fsm_pp6_stage0 : begin
            if ((~((ap_enable_reg_pp6_iter1 == 1'b0) & (1'b0 == ap_block_pp6_stage0_subdone) & (icmp_ln21_fu_893_p2 == 1'd1) & (ap_enable_reg_pp6_iter0 == 1'b1)) & ~((ap_enable_reg_pp6_iter1 == 1'b0) & (1'b0 == ap_block_pp6_stage0_subdone) & (ap_enable_reg_pp6_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp6_stage0;
            end else if ((((ap_enable_reg_pp6_iter1 == 1'b0) & (1'b0 == ap_block_pp6_stage0_subdone) & (icmp_ln21_fu_893_p2 == 1'd1) & (ap_enable_reg_pp6_iter0 == 1'b1)) | ((ap_enable_reg_pp6_iter1 == 1'b0) & (1'b0 == ap_block_pp6_stage0_subdone) & (ap_enable_reg_pp6_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp6_stage0;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & (regslice_both_data_OUT_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln108_1_fu_644_p2 = (indvar_flatten7_reg_379 + 14'd1);

assign add_ln108_fu_656_p2 = (ap_phi_mux_i_3_phi_fu_394_p4 + 9'd1);

assign add_ln109_fu_684_p2 = (select_ln108_fu_668_p3 + 6'd1);

assign add_ln10_fu_518_p2 = (i_1_reg_335 + 14'd1);

assign add_ln110_1_fu_721_p2 = (add_ln110_fu_708_p2 + zext_ln110_1_fu_718_p1);

assign add_ln110_fu_708_p2 = (tmp_2_fu_690_p3 + zext_ln110_fu_704_p1);

assign add_ln17_fu_870_p2 = (i_5_reg_445 + 14'd1);

assign add_ln21_fu_887_p2 = (i_6_reg_456 + 14'd1);

assign add_ln37_1_fu_535_p2 = (indvar_flatten_reg_346 + 14'd1);

assign add_ln37_fu_547_p2 = (ap_phi_mux_i_2_phi_fu_361_p4 + 9'd1);

assign add_ln38_fu_575_p2 = (select_ln37_fu_559_p3 + 6'd1);

assign add_ln39_1_fu_617_p2 = (tmp_1_fu_588_p3 + j_cast_fu_614_p1);

assign add_ln39_fu_627_p2 = (zext_ln39_fu_623_p1 + tmp_fu_581_p3);

assign add_ln40_1_fu_608_p2 = (add_ln40_fu_599_p2 + zext_ln40_2_fu_605_p1);

assign add_ln40_fu_599_p2 = (tmp_fu_581_p3 + zext_ln40_1_fu_595_p1);

assign add_ln59_1_fu_774_p2 = (indvar_flatten15_reg_412 + 14'd1);

assign add_ln59_fu_786_p2 = (ap_phi_mux_i_4_phi_fu_427_p4 + 9'd1);

assign add_ln60_fu_814_p2 = (select_ln59_fu_798_p3 + 6'd1);

assign add_ln61_fu_859_p2 = (zext_ln62_2_fu_844_p1 + tmp_4_fu_820_p3);

assign add_ln62_1_fu_847_p2 = (add_ln62_fu_838_p2 + zext_ln62_2_fu_844_p1);

assign add_ln62_fu_838_p2 = (tmp_4_fu_820_p3 + zext_ln62_1_fu_834_p1);

assign add_ln6_fu_501_p2 = (i_reg_324 + 14'd1);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp5_stage0 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp6_stage0 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp5_stage0_01001 = (((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (ap_enable_reg_pp5_iter2 == 1'b1) & (data_OUT_TREADY_int_regslice == 1'b0)) | ((icmp_ln17_reg_1097 == 1'd0) & (ap_enable_reg_pp5_iter1 == 1'b1) & (data_OUT_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp5_stage0_11001 = (((ap_enable_reg_pp5_iter2 == 1'b1) & ((1'b1 == ap_block_state27_io) | ((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp5_iter1 == 1'b1) & ((1'b1 == ap_block_state26_io) | ((icmp_ln17_reg_1097 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp5_stage0_subdone = (((ap_enable_reg_pp5_iter2 == 1'b1) & ((1'b1 == ap_block_state27_io) | ((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp5_iter1 == 1'b1) & ((1'b1 == ap_block_state26_io) | ((icmp_ln17_reg_1097 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp6_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp6_stage0_01001 = (((icmp_ln21_reg_1116 == 1'd0) & (ap_enable_reg_pp6_iter1 == 1'b1) & (data_OUT_TREADY_int_regslice == 1'b0)) | ((data_OUT_TREADY_int_regslice == 1'b0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0) & (ap_enable_reg_pp6_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp6_stage0_11001 = (((ap_enable_reg_pp6_iter1 == 1'b1) & ((1'b1 == ap_block_state30_io) | ((icmp_ln21_reg_1116 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp6_iter2 == 1'b1) & ((1'b1 == ap_block_state31_io) | ((data_OUT_TREADY_int_regslice == 1'b0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0)))));
end

always @ (*) begin
    ap_block_pp6_stage0_subdone = (((ap_enable_reg_pp6_iter1 == 1'b1) & ((1'b1 == ap_block_state30_io) | ((icmp_ln21_reg_1116 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp6_iter2 == 1'b1) & ((1'b1 == ap_block_state31_io) | ((data_OUT_TREADY_int_regslice == 1'b0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0)))));
end

assign ap_block_state13_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp3_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp3_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp3_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2 = ((icmp_ln6_fu_507_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0));
end

assign ap_block_state21_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp4_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp4_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp5_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state26_io = ((icmp_ln17_reg_1097 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state26_pp5_stage0_iter1 = ((icmp_ln17_reg_1097 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state27_io = ((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state27_pp5_stage0_iter2 = ((icmp_ln17_reg_1097_pp5_iter1_reg == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

assign ap_block_state29_pp6_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state30_io = ((icmp_ln21_reg_1116 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state30_pp6_stage0_iter1 = ((icmp_ln21_reg_1116 == 1'd0) & (data_OUT_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state31_io = ((data_OUT_TREADY_int_regslice == 1'b0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_block_state31_pp6_stage0_iter2 = ((data_OUT_TREADY_int_regslice == 1'b0) & (icmp_ln21_reg_1116_pp6_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_block_state4 = ((icmp_ln10_fu_524_p2 == 1'd0) & (data_IN_TVALID_int_regslice == 1'b0));
end

assign ap_block_state6_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_enable_pp5 = (ap_idle_pp5 ^ 1'b1);

assign ap_enable_pp6 = (ap_idle_pp6 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_IN_TREADY = regslice_both_data_IN_U_ack_in;

assign data_OUT_TVALID = regslice_both_data_OUT_U_vld_out;

assign grp_fft_fu_479_ap_start = grp_fft_fu_479_ap_start_reg;

assign grp_fft_fu_479_grp_fu_1130_p_dout0 = grp_fu_1130_p2;

assign grp_fft_fu_479_grp_fu_1134_p_dout0 = grp_fu_1134_p2;

assign grp_fft_fu_479_grp_fu_1146_p_dout0 = grp_fu_1146_p2;

assign grp_fft_fu_479_grp_fu_1150_p_dout0 = grp_fu_1150_p2;

assign grp_fu_1138_p0 = grp_matchedFilter_fu_467_grp_fu_1138_p_din0;

assign grp_fu_1138_p1 = grp_matchedFilter_fu_467_grp_fu_1138_p_din1;

assign grp_fu_1142_p0 = grp_matchedFilter_fu_467_grp_fu_1142_p_din0;

assign grp_fu_1142_p1 = grp_matchedFilter_fu_467_grp_fu_1142_p_din1;

assign grp_fu_1146_p0 = grp_fft_fu_479_grp_fu_1146_p_din0;

assign grp_fu_1146_p1 = grp_fft_fu_479_grp_fu_1146_p_din1;

assign grp_fu_1150_p0 = grp_fft_fu_479_grp_fu_1150_p_din0;

assign grp_fu_1150_p1 = grp_fft_fu_479_grp_fu_1150_p_din1;

assign grp_matchedFilter_fu_467_ap_start = grp_matchedFilter_fu_467_ap_start_reg;

assign grp_matchedFilter_fu_467_grp_fu_1138_p_dout0 = grp_fu_1138_p2;

assign grp_matchedFilter_fu_467_grp_fu_1142_p_dout0 = grp_fu_1142_p2;

assign grp_matchedFilter_fu_467_grp_fu_739_p_dout0 = grp_fu_739_p2;

assign grp_matchedFilter_fu_467_grp_fu_748_p_dout0 = grp_fu_748_p2;

assign grp_matmul_fu_491_ap_start = grp_matmul_fu_491_ap_start_reg;

assign grp_matmul_fu_491_grp_fu_1130_p_dout0 = grp_fu_1130_p2;

assign grp_matmul_fu_491_grp_fu_1134_p_dout0 = grp_fu_1134_p2;

assign hamming_coeff_M_real_V_address0 = j_1_cast_fu_714_p1;

assign i_1_cast_fu_530_p1 = i_1_reg_335;

assign i_5_cast_fu_882_p1 = i_5_reg_445;

assign i_6_cast_fu_899_p1 = i_6_reg_456;

assign i_cast_fu_513_p1 = i_reg_324;

assign icmp_ln108_fu_650_p2 = ((indvar_flatten7_reg_379 == 14'd12207) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_662_p2 = ((j_1_reg_401 == 6'd39) ? 1'b1 : 1'b0);

assign icmp_ln10_fu_524_p2 = ((i_1_reg_335 == 14'd12520) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_876_p2 = ((i_5_reg_445 == 14'd10016) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_893_p2 = ((i_6_reg_456 == 14'd10016) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_541_p2 = ((indvar_flatten_reg_346 == 14'd12520) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_553_p2 = ((j_reg_368 == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_780_p2 = ((indvar_flatten15_reg_412 == 14'd10016) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_792_p2 = ((j_2_reg_434 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_507_p2 = ((i_reg_324 == 14'd12520) ? 1'b1 : 1'b0);

assign j_1_cast_fu_714_p1 = select_ln108_reg_971;

assign j_cast_fu_614_p1 = select_ln37_reg_929;

assign select_ln108_1_fu_676_p3 = ((icmp_ln109_fu_662_p2[0:0] == 1'b1) ? add_ln108_fu_656_p2 : ap_phi_mux_i_3_phi_fu_394_p4);

assign select_ln108_fu_668_p3 = ((icmp_ln109_fu_662_p2[0:0] == 1'b1) ? 6'd0 : j_1_reg_401);

assign select_ln37_1_fu_567_p3 = ((icmp_ln38_fu_553_p2[0:0] == 1'b1) ? add_ln37_fu_547_p2 : ap_phi_mux_i_2_phi_fu_361_p4);

assign select_ln37_fu_559_p3 = ((icmp_ln38_fu_553_p2[0:0] == 1'b1) ? 6'd0 : j_reg_368);

assign select_ln59_1_fu_806_p3 = ((icmp_ln60_fu_792_p2[0:0] == 1'b1) ? add_ln59_fu_786_p2 : ap_phi_mux_i_4_phi_fu_427_p4);

assign select_ln59_fu_798_p3 = ((icmp_ln60_fu_792_p2[0:0] == 1'b1) ? 6'd0 : j_2_reg_434);

assign sext_ln1118_1_fu_745_p1 = $signed(p_r_M_imag_V_2_reg_1015);

assign sext_ln1118_fu_736_p1 = $signed(p_r_M_real_V_1_reg_1010);

assign tmp_1_fu_588_p3 = {{select_ln37_1_reg_935}, {3'd0}};

assign tmp_2_fu_690_p3 = {{select_ln108_1_reg_977}, {5'd0}};

assign tmp_3_fu_697_p3 = {{select_ln108_1_reg_977}, {3'd0}};

assign tmp_4_fu_820_p3 = {{select_ln59_1_reg_1065}, {5'd0}};

assign tmp_5_fu_827_p3 = {{select_ln59_1_reg_1065}, {3'd0}};

assign tmp_fu_581_p3 = {{select_ln37_1_reg_935}, {5'd0}};

assign zext_ln110_1_fu_718_p1 = select_ln108_reg_971;

assign zext_ln110_2_fu_727_p1 = add_ln110_1_fu_721_p2;

assign zext_ln110_fu_704_p1 = tmp_3_fu_697_p3;

assign zext_ln1118_fu_733_p1 = hamming_coeff_M_real_V_load_reg_1020;

assign zext_ln39_fu_623_p1 = add_ln39_1_fu_617_p2;

assign zext_ln40_1_fu_595_p1 = tmp_1_fu_588_p3;

assign zext_ln40_2_fu_605_p1 = select_ln37_reg_929;

assign zext_ln40_3_fu_639_p1 = add_ln40_1_reg_947;

assign zext_ln40_fu_633_p1 = add_ln39_fu_627_p2;

assign zext_ln62_1_fu_834_p1 = tmp_5_fu_827_p3;

assign zext_ln62_2_fu_844_p1 = select_ln59_reg_1060;

assign zext_ln62_3_fu_853_p1 = add_ln62_1_fu_847_p2;

assign zext_ln62_fu_865_p1 = add_ln61_reg_1087;

always @ (posedge ap_clk) begin
    zext_ln110_2_reg_989[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln110_2_reg_989_pp3_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln110_2_reg_989_pp3_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln110_2_reg_989_pp3_iter4_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //top
